# This file is generated by OwnBase release CI. DO NOT EDIT.
cask "ownbase" do
  version "0.5.6"

  on_macos do
    on_intel do
      sha256 "aacfc0632f651b2b8490abd41ad359f8ff9143f5ea6a39789181901673e92fa4"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-x86_64-apple-darwin.dmg"
    end
    on_arm do
      sha256 "47217e81c8c7dea6e9c1c9899920cebf3287bd5773a82a1574353bbb87d0b84f"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-aarch64-apple-darwin.dmg"
    end
  end

  name "OwnBase"
  desc "Set up a Base, watch its health, and replay every session opened on it"
  homepage "https://ownbase.ai"

  depends_on macos: :big_sur

  app "OwnBase.app"

  # The binaries are not Apple-notarized; strip the quarantine attribute on
  # install so macOS Gatekeeper does not block the first launch.
  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/OwnBase.app"]
    end
  end

  zap trash: [
    "~/Library/Application Support/ai.ownbase.desktop",
    "~/Library/Caches/ai.ownbase.desktop",
    "~/Library/Preferences/ai.ownbase.desktop.plist",
    "~/Library/WebKit/ai.ownbase.desktop",
  ]
end
