# This file was generated by GoReleaser. DO NOT EDIT.
cask "ownbasectl" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "5789f10f7f7ff454abbbcbbad9bf2bf85b58d02215acb32e2ebbb37b6cfd5fd1"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da983e5f8bd534fdfe20fc3a1f85918cd1035be51955c9549ab22483ca99560c"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0b56b9c9676cb39b34ae54a202d82913e40a3ccc4db8f3f3b408058eee524222"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48fad975c24f8db6c0ba3e00a985c7b71eb97f951a82131e5205e5094709e7eb"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ownbasectl"
  desc "Set up, operate, and own your Base — the OwnBase CLI"
  homepage "https://ownbase.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ownbasectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ownbasectl"]
    end
  end

  # No zap stanza required

end
