# This file is generated by OwnBase release CI. DO NOT EDIT.
cask "ownbasectl" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "0616c7298e540e27f53690c512aec59161ece206337249fdafb6969733b10344"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa43dc2bb7bb76fcd54c05b1135acd4507a71b990eae333307ae02237c9c0483"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "73db7f352fe581d95a3754bd91c3a78927246438adde366db89d107f66e1234a"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4dfa55863a2b8d46a4d3c2d124ac1fbafc8a81ad0a03547e5c790b46df1bdedf"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ownbasectl"
  desc "Set up, operate, and own your Base — the OwnBase CLI"
  homepage "https://ownbase.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ownbasectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ownbasectl"]
    end
  end
end
