# This file was generated by GoReleaser. DO NOT EDIT.
cask "ownbasectl" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "38bcc212461428928fbd380a1eb81ef4450680aeda07e586ac8251f791bdf19b"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "efc508594c3ef6fdf4c1338cfd7f80df0b4610fecad862d5b03c1cd59d2821bd"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c97b952324f0189172ecc17783f4e233e6adc766739d916064deb3d313620dbc"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e7e8d38fe9d4bc5b183335e34b5f144aa85fdf6d103a88ad61155000dfa1e33"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/ownbasectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ownbasectl"
  desc "Set up, operate, and own your Base — the OwnBase CLI"
  homepage "https://ownbase.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ownbasectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ownbasectl"]
    end
  end

  # No zap stanza required

end
