# This file is generated by OwnBase release CI. DO NOT EDIT.
cask "ownbase" do
  version "0.5.5"

  on_macos do
    on_intel do
      sha256 "d33a8c9c7cc74afd74b898092d995c7b0de40028da0ced9a702e33f5f240e10b"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-x86_64-apple-darwin.dmg"
    end
    on_arm do
      sha256 "f83c5aa490f0240c4d04f4f4e84af0c96939f3bde72d04e86a632c6ada381741"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-aarch64-apple-darwin.dmg"
    end
  end

  name "OwnBase"
  desc "Set up a Base, watch its health, and replay every session opened on it"
  homepage "https://ownbase.ai"

  depends_on macos: :big_sur

  app "OwnBase.app"

  # The binaries are not Apple-notarized; strip the quarantine attribute on
  # install so macOS Gatekeeper does not block the first launch.
  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/OwnBase.app"]
    end
  end

  zap trash: [
    "~/Library/Application Support/ai.ownbase.desktop",
    "~/Library/Caches/ai.ownbase.desktop",
    "~/Library/Preferences/ai.ownbase.desktop.plist",
    "~/Library/WebKit/ai.ownbase.desktop",
  ]
end
