# This file is generated by OwnBase release CI. DO NOT EDIT.
cask "ownbase" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "7cc45d25be2a01acf5c6f6e16cddc4e54c01978e017dbabc7d3236ce3c063902"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-x86_64-apple-darwin.dmg"
    end
    on_arm do
      sha256 "f2b5168bf19918b0de0cd5b46b3918403ebb281d1cac3df615179ccddb983ce1"
      url "https://github.com/ownbase-ai/ownbase/releases/download/v#{version}/OwnBase-v#{version}-aarch64-apple-darwin.dmg"
    end
  end

  name "OwnBase"
  desc "Set up a Base, watch its health, and replay every session opened on it"
  homepage "https://ownbase.ai"

  depends_on macos: :big_sur

  app "OwnBase.app"

  # The binaries are not Apple-notarized; strip the quarantine attribute on
  # install so macOS Gatekeeper does not block the first launch.
  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/OwnBase.app"]
    end
  end

  zap trash: [
    "~/Library/Application Support/ai.ownbase.desktop",
    "~/Library/Caches/ai.ownbase.desktop",
    "~/Library/Preferences/ai.ownbase.desktop.plist",
    "~/Library/WebKit/ai.ownbase.desktop",
  ]
end
